.TH "spotify" 1
.SH NAME
spotify \- streaming music service client\.
.SH SYNOPSIS
.B spotify
.br
There are no cli options.
.SH DESCRIPTION
This tool is used to listen to the Spotify streaming music service\.
The service is either free and with advertisements, or paid\.
Package is based on a binary package provided on a as-is basis from
some spotify developers.
.SH FILES
.I ~/.cache/spotify
\- can be removed in case of troubles.
.P
.I ~/.config/spotify
\- can be also removed in case of troubles, losing configuration.
.SH BUGS AND SUPPORT
The linux client is unsupported, but there is a community:
.br
http://community.spotify.com
.SH SEE ALSO
http://spotify.com
